"""
Django settings for godakhtar project.

Generated by 'django-admin startproject' using Django 2.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import environ
import json
import logging
from dotenv import load_dotenv
from django.utils.translation import ugettext_lazy as _

logger = logging.getLogger(__name__)

ROOT_DIR = environ.Path(__file__) - 3

env = environ.Env()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


env_path = os.path.join(BASE_DIR, 'deployment', 'local', 'env.list')
if os.path.exists(env_path):
    load_dotenv(env_path)

SETTINGS_DIR = os.path.join(BASE_DIR, 'settings')
with open(os.path.join(SETTINGS_DIR, 'settings.json'), 'r') as settings_file:
    SETTINGS_DICT = json.loads(settings_file.read())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'secret')
# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY =

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = []

LANGUAGES = (
    ('en', _('English')),
    ('fa', _('Persian')),
)

DEBUG = env.bool('DJANGO_DEBUG', True)

# Application definition

INSTALLED_APPS = [
    'products',
    'customers',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'godakhtar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'godakhtar.wsgi.application'

# DB settings
SETTINGS_DICT['postgres']['user'] = os.environ.get('POSTGRES_USER', 'godakhtar')
SETTINGS_DICT['postgres']['password'] = os.environ.get('POSTGRES_PASSWORD', 'a123B456#')
SETTINGS_DICT['postgres']['host'] = os.environ.get('DB_HOST', '127.0.0.1')
SETTINGS_DICT['postgres']['port'] = os.environ.get('DB_PORT', 5432)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': SETTINGS_DICT['postgres']['name'],
        'USER': SETTINGS_DICT['postgres']['user'],
        'HOST': SETTINGS_DICT['postgres']['host'],
        'PORT': SETTINGS_DICT['postgres']['port'],
        'PASSWORD': SETTINGS_DICT['postgres']['password']
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# Local time zone. Choices are
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# though not all of them may be available with every OS.
# In Windows, this must be set to your system time zone.
TIME_ZONE = 'Asia/Tehran'
# https://docs.djangoproject.com/en/dev/ref/settings/#language-code
LANGUAGE_CODE = 'fa-IR'
# https://docs.djangoproject.com/en/dev/ref/settings/#use-i18n
# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/
USE_I18N = True
# https://docs.djangoproject.com/en/dev/ref/settings/#use-l10n
USE_L10N = True
# https://docs.djangoproject.com/en/dev/ref/settings/#use-tz
USE_TZ = False

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = (
    ('en-us', _('English')),
    ('fa-IR', _('Persian')),
)

# Log settings

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '📯[%(levelname)-5s|%(asctime)s|%(name)-12s|%(funcName)s|%(lineno)d] %(message)s',
        },
    },
    'handlers': {

        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },

    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARN',
            'propagate': False,
        },
    },
}

# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10
# }

