# Generated by Django 2.2 on 2019-06-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_auto_20190610_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_documents', models.CharField(blank=True, max_length=127, null=True, verbose_name='QA Documents')),
                ('guaranty', models.CharField(blank=True, max_length=127, null=True, verbose_name='Guaranty')),
                ('warranty', models.CharField(blank=True, max_length=127, null=True, verbose_name='Warranty')),
                ('packaging', models.CharField(blank=True, max_length=5, null=True, verbose_name='Packaging')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer')),
            ],
        ),
    ]
