# Generated by Django 2.2 on 2019-06-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190614_1752'),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
