# Generated by Django 2.2 on 2019-06-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_inquiry_inquiry_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
