# Generated by Django 2.2 on 2019-06-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190614_1752'),
        ('inquiry', '0003_auto_20190616_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='inquiry_products',
        ),
        migrations.CreateModel(
            name='InquiryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.Inquiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
