# Generated by Django 2.2 on 2019-06-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_auto_20190616_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryproducts',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_products', to='inquiry.Inquiry'),
        ),
    ]
