# Generated by Django 2.2 on 2019-06-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_auto_20190616_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inquiries', to='products.Product'),
        ),
    ]
