# Generated by Django 2.2 on 2019-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_auto_20190616_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='client_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Consultant Name'),
        ),
    ]
