# Generated by Django 2.2 on 2019-06-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_auto_20190629_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='customer_priority',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='document_review',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='other_engineering_requirements',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='payment_type',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='tech_level',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='tender_guarantee',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='vendor_list',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='KARFARMA Name'),
        ),
        migrations.AddField(
            model_name='inquiryproducts',
            name='unit_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
