# Generated by Django 2.2 on 2019-04-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'customer'), (2, 'office'), (3, 'person')], verbose_name='Contact Type')),
            ],
        ),
    ]
