# Generated by Django 2.2 on 2019-04-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190426_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
    ]
