# Generated by Django 2.2 on 2019-04-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='label',
            field=models.CharField(choices=[('M', 'Mobile'), ('E', 'E-Mail'), ('A', 'Address'), ('P', 'Phone'), ('W', 'Work'), ('F', 'Fax'), ('S', 'Site'), ('O', 'Office'), ('C', 'Postal Code'), ('D', 'Office Address'), ('F', 'Site Address'), ('H', 'Other')], max_length=1),
        ),
    ]
