# Generated by Django 2.2 on 2019-05-07 22:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_no', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('financial_code', models.CharField(max_length=20, verbose_name='Economical Number')),
                ('national_id', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=20)),
                ('office_address', models.CharField(max_length=255)),
                ('site_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('ceo', models.CharField(max_length=120)),
                ('ceo_office', models.CharField(max_length=20)),
                ('ceo_mobile', models.CharField(max_length=20)),
                ('ceo_email', models.CharField(max_length=120)),
                ('cfo', models.CharField(max_length=120)),
                ('cfo_office', models.CharField(max_length=20)),
                ('cfo_mobile', models.CharField(max_length=20)),
                ('cfo_email', models.CharField(max_length=120)),
                ('logistic', models.CharField(max_length=120)),
                ('logistic_office', models.CharField(max_length=20)),
                ('logistic_mobile', models.CharField(max_length=20)),
                ('logistic_email', models.CharField(max_length=120)),
                ('engineering', models.CharField(max_length=120)),
                ('engineering_office', models.CharField(max_length=20)),
                ('engineering_mobile', models.CharField(max_length=20)),
                ('engineering_email', models.CharField(max_length=120)),
                ('expert', models.CharField(max_length=120)),
                ('expert_office', models.CharField(max_length=20)),
                ('expert_mobile', models.CharField(max_length=20)),
                ('expert_email', models.CharField(max_length=120)),
                ('maintenance_name', models.CharField(max_length=120)),
                ('maintenance_office', models.CharField(max_length=20)),
                ('maintenance_mobile', models.CharField(max_length=20)),
                ('maintenance_email', models.CharField(max_length=120)),
                ('key_persons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('section', models.CharField(choices=[('O', 'Oil'), ('G', 'Gas'), ('P', 'Pertrochemical'), ('R', 'Refinery'), ('E', 'Plant'), ('C', 'Construction'), ('S', 'Steel'), ('H', 'Other')], max_length=1)),
                ('ownership', models.CharField(choices=[('P', 'Private'), ('G', 'Government'), ('S', 'Semi-Private'), ('H', 'Other')], max_length=1)),
                ('owner', models.CharField(max_length=100)),
                ('activity', models.CharField(choices=[('O', 'Operator'), ('C', 'Contractor'), ('S', 'Consultant'), ('H', 'Other')], max_length=1)),
                ('classification', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('acquainted', models.CharField(choices=[('A', 'Abbas'), ('B', 'Bagher')], max_length=1)),
                ('deal_type', models.CharField(max_length=100)),
                ('deal_worth', models.CharField(max_length=100)),
                ('deal_history', models.BooleanField()),
                ('inquiry_history', models.BooleanField()),
                ('deal_comments', models.TextField()),
                ('last_godakhtar_visit', models.DateField()),
                ('last_visit_from_site', models.DateField()),
                ('mechanism', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
