# Generated by Django 2.2 on 2019-04-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_auto_20190426_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('no', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('eco_code', models.CharField(max_length=20, verbose_name='Economical Number')),
                ('section', models.CharField(choices=[('O', 'Oil'), ('G', 'Gas'), ('P', 'Pertrochemical'), ('R', 'Refinery'), ('E', 'Plant'), ('C', 'Construction'), ('S', 'Steel'), ('H', 'Other')], max_length=1)),
                ('ownership', models.CharField(choices=[('P', 'Private'), ('G', 'Government'), ('S', 'Semi-Private'), ('H', 'Other')], max_length=1)),
                ('owner', models.CharField(max_length=100)),
                ('activity', models.CharField(choices=[('O', 'Operator'), ('C', 'Contractor'), ('S', 'Consultant'), ('H', 'Other')], max_length=1)),
                ('classification', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('channel', models.CharField(max_length=100)),
                ('buy_type', models.CharField(max_length=100)),
                ('previous_deal', models.BooleanField()),
                ('sales_comments', models.TextField()),
                ('last_godakhtar_visit', models.DateField()),
                ('last_visit_from_site', models.DateField()),
                ('mechanism', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contact', to='contact.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('O', 'Office'), ('C', 'Central Office'), ('S', 'Site'), ('H', 'Other')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('key_person', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_contact', to='contact.Contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customers.Customer')),
            ],
        ),
    ]
