# Generated by Django 2.2 on 2019-05-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_no', models.CharField(max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=1, null=True)),
                ('financial_code', models.CharField(max_length=20, null=True, verbose_name='Economical Number')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('site_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.CharField(blank=True, max_length=127, null=True)),
                ('ceo', models.CharField(blank=True, max_length=127, null=True)),
                ('ceo_office', models.CharField(blank=True, max_length=20, null=True)),
                ('ceo_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('ceo_email', models.CharField(blank=True, max_length=127, null=True)),
                ('cfo', models.CharField(blank=True, max_length=127, null=True)),
                ('cfo_office', models.CharField(blank=True, max_length=20, null=True)),
                ('cfo_email', models.CharField(blank=True, max_length=127, null=True)),
                ('logistic', models.CharField(blank=True, max_length=127, null=True)),
                ('logistic_office', models.CharField(blank=True, max_length=20, null=True)),
                ('logistic_email', models.CharField(blank=True, max_length=127, null=True)),
                ('engineering', models.CharField(blank=True, max_length=127, null=True)),
                ('engineering_office', models.CharField(blank=True, max_length=20, null=True)),
                ('engineering_email', models.CharField(blank=True, max_length=120, null=True)),
                ('expert', models.CharField(blank=True, max_length=120, null=True)),
                ('expert_office', models.CharField(blank=True, max_length=20, null=True)),
                ('expert_email', models.CharField(blank=True, max_length=120, null=True)),
                ('maintenance_name', models.CharField(blank=True, max_length=120, null=True)),
                ('maintenance_office', models.CharField(blank=True, max_length=20, null=True)),
                ('maintenance_email', models.CharField(blank=True, max_length=120, null=True)),
                ('section', models.CharField(blank=True, choices=[('o', 'Oil'), ('g', 'Gas'), ('p', 'Pertrochemical'), ('r', 'Refinery'), ('e', 'Plant'), ('c', 'Construction'), ('s', 'Steel'), ('h', 'Other')], max_length=1, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('p', 'Private'), ('g', 'Government'), ('s', 'Semi-Private'), ('h', 'Other')], max_length=1, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(blank=True, choices=[('o', 'Operator'), ('c', 'Contractor'), ('s', 'Consultant'), ('h', 'Other')], max_length=1, null=True)),
                ('classification', models.CharField(blank=True, choices=[('g', 'GC'), ('e', 'EPC'), ('f', 'Finance'), ('o', 'Operator'), ('s', 'Store'), ('h', 'Other')], max_length=1, null=True)),
                ('acquainted', models.CharField(blank=True, choices=[('e', 'Expo'), ('w', 'Website'), ('r', 'Recommended By Customers'), ('v', 'Vendor List'), ('h', 'Other')], max_length=1, null=True)),
                ('deal_type', models.CharField(blank=True, choices=[('t', 'Gate'), ('g', 'Globe'), ('c', 'Check'), ('o', 'Ball'), ('b', 'Butterfly'), ('r', 'Repair Service'), ('m', 'Maintenance Service'), ('s', 'Spare Parts'), ('h', 'Other')], max_length=1, null=True)),
                ('deal_worth', models.CharField(blank=True, max_length=127, null=True)),
                ('deal_history', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('z', 'Zero')], max_length=1, null=True)),
                ('inquiry_history', models.CharField(blank=True, choices=[('n', 'No Inquiry'), ('d', 'Has Deal'), ('r', 'Reject')], max_length=1, null=True)),
                ('deal_comments', models.TextField(blank=True, null=True)),
                ('last_godakhtar_visit', models.CharField(blank=True, max_length=127, null=True)),
                ('last_customer_visit', models.CharField(blank=True, max_length=127, null=True)),
                ('mechanism', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=127, null=True)),
                ('comments', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
