# Generated by Django 2.2 on 2019-04-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='no',
            new_name='customer_no',
        ),
    ]
