# Generated by Django 2.2 on 2019-06-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ceo_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ceo_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ceo_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cfo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cfo_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cfo_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engineering',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engineering_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engineering_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expert_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expert_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='logistic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='logistic_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='logistic_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='maintenance_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='maintenance_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='maintenance_office',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=models.CharField(blank=True, choices=[('e', 'End User'), ('c', 'Contractor'), ('s', 'Consultant'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classification',
            field=models.CharField(choices=[('g', 'GC'), ('e', 'EPC'), ('f', 'Trader'), ('o', 'End User'), ('s', 'Store'), ('h', 'Other')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Customer Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='english_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='financial_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Economical Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='oil_section',
            field=models.BooleanField(default=False, verbose_name='Oil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='priority',
            field=models.CharField(blank=True, choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=1, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Website address'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('role', models.CharField(choices=[('c', 'CEO'), ('f', 'CFO'), ('t', 'CTO'), ('e', 'Engineering Manager'), ('m', 'Maintenance Manager'), ('s', 'Expert'), ('h', 'Other')], max_length=2)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=127, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.CharField(choices=[('c', 'Headquarters'), ('o', 'Office'), ('s', 'Site'), ('h', 'Other')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Postal Code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax Number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
