# Generated by Django 2.2 on 2019-06-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190601_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=models.CharField(blank=True, choices=[('e', 'End User'), ('c', 'Contractor'), ('s', 'Consultant'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='english_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='English Name'),
        ),
    ]
