# Generated by Django 2.2 on 2019-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190602_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperson',
            name='email',
            field=models.EmailField(blank=True, max_length=127, null=True),
        ),
    ]
