# Generated by Django 2.2 on 2019-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190601_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='financial_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Economical Number'),
        ),
    ]
