# Generated by Django 2.2 on 2019-05-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190507_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_visit_from_site',
            new_name='last_customer_visit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cfo_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engineering_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expert_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='logistic_mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='maintenance_mobile',
        ),
        migrations.AlterField(
            model_name='customer',
            name='acquainted',
            field=models.CharField(choices=[('E', 'Expo'), ('W', 'Website'), ('R', 'Recommended By Customers'), ('V', 'Vendor List'), ('H', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ceo',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ceo_email',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cfo',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cfo_email',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classification',
            field=models.CharField(choices=[('G', 'GC'), ('E', 'EPC'), ('F', 'Finance'), ('O', 'Operator'), ('S', 'Store'), ('H', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_type',
            field=models.CharField(choices=[('T', 'Gate'), ('G', 'Globe'), ('C', 'Check'), ('O', 'Ball'), ('B', 'Butterfly'), ('R', 'Repair Service'), ('M', 'Maintenance Service'), ('S', 'Spare Parts'), ('H', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='engineering',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inquiry_history',
            field=models.CharField(choices=[('N', 'No Inquiry'), ('D', 'Has Deal'), ('R', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logistic',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logistic_email',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(max_length=127),
        ),
    ]
