# Generated by Django 2.2 on 2019-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190601_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='classification',
            field=models.CharField(blank=True, choices=[('g', 'GC'), ('e', 'EPC'), ('f', 'Trader'), ('o', 'End User'), ('s', 'Store'), ('h', 'Other')], max_length=1, null=True),
        ),
    ]
