# Generated by Django 2.2 on 2019-06-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190605_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='keyperson',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_persons', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='customers.Customer'),
        ),
    ]
