# Generated by Django 2.2 on 2019-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190512_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deal_history',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('Z', 'Zero')], max_length=1),
        ),
    ]
