# Generated by Django 2.2 on 2019-06-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20190605_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
