# Generated by Django 2.2 on 2019-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_personnel_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='English Name'),
        ),
    ]
