# Generated by Django 2.2 on 2019-06-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190610_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('c', 'CEO'), ('f', 'CFO'), ('t', 'CTO'), ('e', 'Engineering Manager'), ('m', 'Maintenance Manager'), ('p', 'Project Manager'), ('s', 'Expert'), ('h', 'Other')], max_length=2),
        ),
    ]
