# Generated by Django 2.2 on 2019-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190513_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deal_worth',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_customer_visit',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_godakhtar_visit',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
