# Generated by Django 2.2 on 2019-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20190513_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acquainted',
            field=models.CharField(blank=True, choices=[('e', 'Expo'), ('w', 'Website'), ('r', 'Recommended By Customers'), ('v', 'Vendor List'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='activity',
            field=models.CharField(blank=True, choices=[('o', 'Operator'), ('c', 'Contractor'), ('s', 'Consultant'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classification',
            field=models.CharField(blank=True, choices=[('g', 'GC'), ('e', 'EPC'), ('f', 'Finance'), ('o', 'Operator'), ('s', 'Store'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_history',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('z', 'Zero')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('t', 'Gate'), ('g', 'Globe'), ('c', 'Check'), ('o', 'Ball'), ('b', 'Butterfly'), ('r', 'Repair Service'), ('m', 'Maintenance Service'), ('s', 'Spare Parts'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inquiry_history',
            field=models.CharField(blank=True, choices=[('n', 'No Inquiry'), ('d', 'Has Deal'), ('r', 'Reject')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ownership',
            field=models.CharField(blank=True, choices=[('p', 'Private'), ('g', 'Government'), ('s', 'Semi-Private'), ('h', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='priority',
            field=models.CharField(blank=True, choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='section',
            field=models.CharField(blank=True, choices=[('o', 'Oil'), ('g', 'Gas'), ('p', 'Pertrochemical'), ('r', 'Refinery'), ('e', 'Plant'), ('c', 'Construction'), ('s', 'Steel'), ('h', 'Other')], max_length=1, null=True),
        ),
    ]
