# Generated by Django 2.2 on 2019-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20190513_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_comments',
            field=models.TextField(null=True),
        ),
    ]
