# Generated by Django 2.2 on 2019-05-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20190513_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='financial_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Economical Number'),
        ),
    ]
