# Generated by Django 2.2 on 2019-05-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_keyperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyperson',
            name='phone',
        ),
    ]
