<<<<<<< HEAD
# Generated by Django 2.2 on 2019-05-20 21:59
=======
# Generated by Django 2.2 on 2019-05-20 05:46
>>>>>>> f398b248198cbb57d405739c83f9097b4ff0b18e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_keyperson_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='key_persons',
        ),
    ]
