# Generated by Django 2.2 on 2019-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_material', models.CharField(choices=[('WCB', 'WCB'), ('A105', 'A105'), ('SS304', 'SS304'), ('SS316', 'SS316'), ('CF8', 'CF8'), ('CF3', 'CF3'), ('CF8M', 'CF8M'), ('CF3M', 'CF3M'), ('CF8C', 'CF8C'), ('LCB', 'LCB'), ('LCC', 'LCC'), ('Al-Bronz', 'Al-Bronz'), ('WCC', 'WCC'), ('WC9', 'WC9'), ('WC6', 'WC6'), ('C5', 'C5'), ('C12', 'C12'), ('Cast Iron', 'Cast Iron'), ('Inconel', 'Inconel'), ('Monel', 'Monel'), ('Hatelloy', 'Hatelloy'), ('A351-CK3MCuN', 'A351-CK3MCuN'), ('A351-CD4MCu', 'A351-CD4MCu'), ('A890-1A', 'A890-1A'), ('A890-4A', 'A890-4A')], max_length=32, verbose_name='Body Material')),
                ('operation', models.CharField(choices=[('GO', 'Gear Operated'), ('LO', 'Lever Operated'), ('EA', 'Electrical Actuator'), ('PA', 'Pnumatic Actuator'), ('GOOA', 'Gas Over Oil Actuator'), ('BS', 'Bare Shaft'), ('H', 'Handwheel'), ('EAM', 'Electrical Actuator with master station(MOV)')], max_length=9, verbose_name='Operation')),
                ('product_class', models.CharField(choices=[('125', '125'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('400', '400'), ('600', '600'), ('800', '800'), ('900', '900'), ('1500', '1500'), ('2500', '2500'), ('3000', '3000'), ('4500', '4500'), ('5000', '5000'), ('10000', '10000'), ('PN10', 'PN10'), ('PN16', 'PN16'), ('PN20', 'PN20'), ('PN50', 'PN50')], max_length=9, verbose_name='Class')),
                ('product_connection', models.CharField(choices=[('Flange / RF', 'Flange / RF'), ('Flange / FF', 'Flange / FF'), ('Flange / RTJ', 'Flange / RTJ'), ('Flange / Large Femal', 'Flange / Large Femal'), ('Flange / Large Mal', 'Flange / Large Mal'), ('Grove Flange', 'Grove Flange'), ('Wafer / RF', 'Wafer / RF'), ('Wafer / FF', 'Wafer / FF'), ('Butt weld', 'Butt weld'), ('Socket Weld', 'Socket Weld'), ('Scrowed', 'Scrowed'), ('Threaded', 'Threaded'), ('Lug', 'Lug'), ('Semi Lug', 'Semi Lug'), ('SW / Thrd', 'SW / Thrd')], max_length=22, verbose_name='Connection')),
                ('product_type', models.CharField(choices=[('3WB', '3 Way Ball Valve'), ('B', 'Ball Valve'), ('BGa', 'Bellowse Gate Valve'), ('BGl', 'Bellowse Globe Valve'), ('BF', 'Butterfly valve'), ('C', 'Check Valve'), ('CrB', 'Cryogenic Ball Valve'), ('CrBf', 'Cryogenic Butterfly Valve'), ('CrC', 'Cryogenic Check Valve'), ('CrGa', 'Cryogenic Gate Valve'), ('CrGl', 'Cryogenic Globe Valve'), ('Ga', 'Gate Valve'), ('Gl', 'Globe'), ('KG', 'Knife Gate Valve'), ('P', 'Plug Valve'), ('TCG', 'Through Conduit Gate Valve')], max_length=9)),
                ('trim_material', models.CharField(choices=[('WCB + ENP', 'WCB + ENP'), ('A105 + ENP', 'A105 + ENP'), ('LF2+ENP', 'LF2+ENP'), ('SS316+TC', 'SS316+TC'), ('SS316', 'SS316'), ('410', '410'), ('OT1', 'Overlay Trim No. #1'), ('OT2', 'Overlay Trim No. #2'), ('OT3', 'Overlay Trim No. #3'), ('OT4', 'Overlay Trim No. #4'), ('OT5', 'Overlay Trim No. #5'), ('OT5A', 'Overlay Trim No. #5A'), ('OT6', 'Overlay Trim No. #6'), ('OT7', 'Overlay Trim No. #7'), ('OT8', 'Overlay Trim No. #8'), ('OT8A', 'Overlay Trim No. #8A'), ('OT9', 'Overlay Trim No. #9'), ('OT10', 'Overlay Trim No. #10'), ('OT11', 'Overlay Trim No. #11'), ('OT12', 'Overlay Trim No. #12'), ('OT13', 'Overlay Trim No. #13'), ('OT14', 'Overlay Trim No. #14'), ('OT15', 'Overlay Trim No. #15'), ('OT16', 'Overlay Trim No. #16'), ('OT17', 'Overlay Trim No. #17'), ('OT18', 'Overlay Trim No. #18')], max_length=32, verbose_name='Trim Material')),
            ],
        ),
    ]
