# Generated by Django 2.2 on 2019-05-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trim_material',
        ),
    ]
