# Generated by Django 2.2 on 2019-06-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190531_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('type', models.CharField(choices=[('n', 'Numeric'), ('c', 'Choices'), ('t', 'Text')], max_length=1)),
                ('validator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=63)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_attributes',
            field=models.ManyToManyField(to='products.Attribute'),
        ),
    ]
