# Generated by Django 2.2 on 2019-05-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190520_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operation',
            field=models.CharField(choices=[('GO', 'Gear Operated'), ('LO', 'Lever Operated'), ('EA', 'Electrical Actuator'), ('PA', 'Pnumatic Actuator'), ('GOOA', 'Gas Over Oil Actuator'), ('BS', 'Bare Shaft'), ('H', 'Handwheel'), ('EAM', 'Electrical Actuator with master station(MOV)')], max_length=9, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.CharField(choices=[('125', '125'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('400', '400'), ('600', '600'), ('800', '800'), ('900', '900'), ('1500', '1500'), ('2500', '2500'), ('3000', '3000'), ('4500', '4500'), ('5000', '5000'), ('10000', '10000'), ('PN10', 'PN10'), ('PN16', 'PN16'), ('PN20', 'PN20'), ('PN50', 'PN50')], max_length=9, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_connection',
            field=models.CharField(choices=[('Flange / RF', 'Flange / RF'), ('Flange / FF', 'Flange / FF'), ('Flange / RTJ', 'Flange / RTJ'), ('Flange / Large Femal', 'Flange / Large Femal'), ('Flange / Large Mal', 'Flange / Large Mal'), ('Grove Flange', 'Grove Flange'), ('Wafer / RF', 'Wafer / RF'), ('Wafer / FF', 'Wafer / FF'), ('Butt weld', 'Butt weld'), ('Socket Weld', 'Socket Weld'), ('Scrowed', 'Scrowed'), ('Threaded', 'Threaded'), ('Lug', 'Lug'), ('Semi Lug', 'Semi Lug'), ('SW / Thrd', 'SW / Thrd')], max_length=22, verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1 1/2', '1 1/2'), ('2', '2'), ('2 1/2', '2 1/2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('72', '72'), ('74', '74'), ('76', '76'), ('78', '78'), ('80', '80'), ('82', '82'), ('84', '84'), ('86', '86'), ('88', '88'), ('90', '90'), ('92', '92'), ('94', '94'), ('96', '96'), ('98', '98'), ('100', '100'), ('1*1/2', '1*1/2'), ('2*1', '2*1'), ('3*2', '3*2'), ('4*3', '4*3'), ('6*4', '6*4'), ('8*6', '8*6'), ('10*8', '10*8'), ('12*10', '12*10'), ('14*10', '14*10'), ('16*12', '16*12'), ('18*14', '18*14'), ('20*16', '20*16'), ('22*18', '22*18'), ('24*20', '24*20'), ('26*22', '26*22'), ('28*24', '28*24'), ('30*26', '30*26'), ('32*26', '32*26'), ('34*28', '34*28'), ('36*30', '36*30'), ('38*32', '38*32'), ('40*34', '40*34'), ('42*36', '42*36'), ('44*38', '44*38'), ('46*40', '46*40'), ('48*42', '48*42'), ('50*44', '50*44'), ('52*46', '52*46'), ('54*48', '54*48'), ('56*50', '56*50'), ('58*52', '58*52'), ('60*54', '60*54')], max_length=9, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('3WB', '3 Way Ball Valve'), ('B', 'Ball Valve'), ('BGa', 'Bellowse Gate Valve'), ('BGl', 'Bellowse Globe Valve'), ('BF', 'Butterfly valve'), ('C', 'Check Valve'), ('CrB', 'Cryogenic Ball Valve'), ('CrBf', 'Cryogenic Butterfly Valve'), ('CrC', 'Cryogenic Check Valve'), ('CrGa', 'Cryogenic Gate Valve'), ('CrGl', 'Cryogenic Globe Valve'), ('Ga', 'Gate Valve'), ('Gl', 'Globe'), ('KG', 'Knife Gate Valve'), ('P', 'Plug Valve'), ('TCG', 'Through Conduit Gate Valve')], max_length=9, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='DescriptionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Description')),
            ],
        ),
    ]
