# Generated by Django 2.2 on 2019-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190605_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='validator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
