# Generated by Django 2.2 on 2019-05-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190520_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='values',
        ),
    ]
