# Generated by Django 2.2 on 2019-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190605_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='operation',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('.25', '1/4'), ('.5', '1/2'), ('.75', '3/4'), ('1', '1'), ('1.5', '1 1/2'), ('2', '2'), ('2.5', '2 1/2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('72', '72'), ('74', '74'), ('76', '76'), ('78', '78'), ('80', '80'), ('82', '82'), ('84', '84'), ('86', '86'), ('88', '88'), ('90', '90'), ('92', '92'), ('94', '94'), ('96', '96'), ('98', '98'), ('100', '100')], default='', max_length=9, verbose_name='Product Size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('n', 'Numeric'), ('c', 'Choices'), ('t', 'Text')], max_length=1, verbose_name='Attribute Choices'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='validator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Validator'),
        ),
        migrations.AlterField(
            model_name='attributechoices',
            name='value',
            field=models.CharField(max_length=63, verbose_name='Attribute Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_attributes',
            field=models.ManyToManyField(to='products.Attribute', verbose_name='Available Attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('3WB', '3 Way Ball Valve'), ('B', 'Ball Valve'), ('BGa', 'Bellowse Gate Valve'), ('BGl', 'Bellowse Globe Valve'), ('BF', 'Butterfly valve'), ('C', 'Check Valve'), ('CrB', 'Cryogenic Ball Valve'), ('CrBf', 'Cryogenic Butterfly Valve'), ('CrC', 'Cryogenic Check Valve'), ('CrGa', 'Cryogenic Gate Valve'), ('CrGl', 'Cryogenic Globe Valve'), ('Ga', 'Gate Valve'), ('Gl', 'Globe'), ('KG', 'Knife Gate Valve'), ('P', 'Plug Valve'), ('TCG', 'Through Conduit Gate Valve')], max_length=9, verbose_name='Product Type'),
        ),
    ]
