# Generated by Django 2.2 on 2019-05-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_description_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('3WB', '3 Way Ball Valve'), ('B', 'Ball Valve'), ('BGa', 'Bellowse Gate Valve'), ('BGl', 'Bellowse Globe Valve'), ('BF', 'Butterfly valve'), ('C', 'Check Valve'), ('CrB', 'Cryogenic Ball Valve'), ('CrBf', 'Cryogenic Butterfly Valve'), ('CrC', 'Cryogenic Check Valve'), ('CrGa', 'Cryogenic Gate Valve'), ('CrGl', 'Cryogenic Globe Valve'), ('Ga', 'Gate Valve'), ('Gl', 'Globe'), ('KG', 'Knife Gate Valve'), ('P', 'Plug Valve'), ('TCG', 'Through Conduit Gate Valve')], max_length=9, verbose_name='Type')),
                ('descriptions', models.ManyToManyField(to='products.Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
        ),
    ]
