# Generated by Django 2.2 on 2019-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190605_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.CharField(choices=[('125', '125'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('400', '400'), ('600', '600'), ('800', '800'), ('900', '900'), ('1500', '1500'), ('2500', '2500'), ('3000', '3000'), ('4500', '4500'), ('5000', '5000'), ('10000', '10000'), ('PN10', 'PN10'), ('PN16', 'PN16'), ('PN20', 'PN20'), ('PN50', 'PN50')], max_length=6, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_connection',
            field=models.CharField(choices=[('Fe', 'Flange'), ('WF', 'Wafer'), ('BW', 'Butt weld'), ('SW', 'Socket Weld'), ('SE', 'Scrowed'), ('TH', 'Threaded'), ('LUG', 'Lug')], max_length=3, verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1 1/2', '1 1/2'), ('2', '2'), ('2 1/2', '2 1/2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64'), ('66', '66'), ('68', '68'), ('70', '70'), ('72', '72'), ('74', '74'), ('76', '76'), ('78', '78'), ('80', '80'), ('82', '82'), ('84', '84'), ('86', '86'), ('88', '88'), ('90', '90'), ('92', '92'), ('94', '94'), ('96', '96'), ('98', '98'), ('100', '100')], max_length=5, verbose_name='Product Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('BV', 'Ball Valve'), ('GV', 'Bellowse Gate Valve'), ('GLV', 'Bellowse Globe Valve'), ('BUV', 'Butterfly valve'), ('CV', 'Check Valve'), ('CryoBV', 'Cryogenic Ball Valve'), ('CryoBUV', 'Cryogenic Butterfly Valve'), ('CryoBUV', 'Cryogenic Butterfly Valve'), ('CryoCV', 'Cryogenic Check Valve'), ('CryoGV', 'Cryogenic Gate Valve'), ('CryoGLV', 'Cryogenic Globe Valve'), ('GV', 'Gate Valve'), ('GLV', 'Globe'), ('KFGV', 'Knife Gate Valve'), ('PV', 'Plug Valve'), ('TCGV', 'Through Conduit Gate Valve')], max_length=8, verbose_name='Product Type'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_type', 'product_class', 'product_connection', 'product_size')},
        ),
    ]
