# Generated by Django 2.2 on 2019-06-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190605_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoices',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_choices', to='products.Attribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_attributes',
            field=models.ManyToManyField(related_name='product', to='products.Attribute', verbose_name='Available Attributes'),
        ),
    ]
