# Generated by Django 2.2 on 2019-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190605_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_attributes',
            field=models.ManyToManyField(blank=True, related_name='product', to='products.Attribute', verbose_name='Available Attributes'),
        ),
    ]
