# Generated by Django 2.2 on 2019-06-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190613_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Product Name'),
        ),
    ]
